### ISSUE TITLE
Support for `onlyDirectories` option

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#1]
The option is described here: https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#onlydirectories

I would like to use it to migrate the following: https://github.com/Thinkmill/manypkg/blob/main/packages/tools/src/expandPackageGlobs.ts

**Comment by SuperchupuDev** [comment]
added in 0.1.2

**Comment by benmccann** [comment]
amazing! thank you!
