### ISSUE TITLE
Skip symlinks

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#26]
I think globby/fast-glob excludes symlinks:
https://github.com/mrmlnc/fast-glob/blob/da648078ae87bce81fcd42e64d5b2b1360c47b09/src/providers/filters/deep.ts#L38

It could potentially be an option whether to skip them or treat them as a file. It'd probably be nice to skip by default though to match the behavior of globby/fast-glob

I tried to convert cspell to use tinyglobby, but its tests failed because of this (https://github.com/streetsidesoftware/cspell/pull/6167)

**Comment by SuperchupuDev** [comment]
opened thecodrr/fdir#115 for upstream support
