### ISSUE TITLE
`isDynamicPattern` support

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#28]
https://github.com/vitejs/vite/blob/8c661b20e92f33eb2e3ba3841b20dd6f6076f1ef/packages/vite/src/node/optimizer/index.ts#L836
https://github.com/vitejs/vite/blob/8c661b20e92f33eb2e3ba3841b20dd6f6076f1ef/packages/vite/src/node/optimizer/scan.ts#L261

**Comment by hi-ogawa** [comment]
It looks like `fast-glob` has implemented its own logic for `isDynamicPattern` https://github.com/mrmlnc/fast-glob/blob/da648078ae87bce81fcd42e64d5b2b1360c47b09/src/utils/pattern.ts#L35, but I wonder if this can be also implemented using [`picomatch.scan`](https://github.com/micromatch/picomatch/?tab=readme-ov-file#scan).

**Comment by SuperchupuDev** [comment]
> It looks like `fast-glob` has implemented its own logic and regex for `isDynamicPattern` [mrmlnc/fast-glob@`da64807`/src/utils/pattern.ts#L35](https://github.com/mrmlnc/fast-glob/blob/da648078ae87bce81fcd42e64d5b2b1360c47b09/src/utils/pattern.ts#L35), but I wonder if this can be also implemented using [`picomatch.scan`](https://github.com/micromatch/picomatch/?tab=readme-ov-file#scan), which seems to return what glob pattern includes.

managed to implement it with `picomatch.scan` and it seems to work well! thanks for the suggestion. the implementation has some minor differences with `fast-glob`'s though that i think are more accurate with what the function is supposed to do
