### ISSUE TITLE
Possible bug: braces does not work

### ISSUE THREAD

**Issue by sapphi-red** [SuperchupuDev/tinyglobby#34]
I expect `'./dir/*.{js,ts}'` to only match `./dir/a.js` and `./dir/b.js` like fast-glob does, but it matches everything in the working directory.
https://stackblitz.com/edit/node-dkpzkw?file=index.js
This probably a bug?

Also it would be nice if there's a explanation which syntax is supported on the README like [picomatch does](https://github.com/micromatch/picomatch?tab=readme-ov-file#globbing-features).

**Comment by SuperchupuDev** [comment]
that's weird, it's supposed to work. will check

**Comment by SuperchupuDev** [comment]
ah, i see now. tinyglobby only supports an array of patterns right now, using plain strings is not supported. it works if you change it to an array
![image](https://github.com/user-attachments/assets/ec4c03a6-f92b-4be7-aced-6a37adb3883e)

**Comment by SuperchupuDev** [comment]
to avoid this very easy to do mistake in the future, i've just added support for plain strings as patterns in 1c7069e

**Comment by sapphi-red** [comment]
Oh, I should definitely use TypeScript 😅 Thanks for adding support!
