### ISSUE TITLE
Support `onlyFiles`

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#4]
Needed to switch over `vite-plugin-pwa`:
https://github.com/vite-pwa/vite-plugin-pwa/blob/6845dc7ab8c8927918a7431f4f8cb296dd399ca2/src/assets.ts#L97

vite-plugin-pwa is downloaded ~1m/mo and I think we have a good chance to get it switched over since I've been a little involved with it in the past and the maintainers of it, vite, and e18e overlap a good amount

**Comment by SuperchupuDev** [comment]
i fail to understand how `unique` even exists - is it possible to have multiple files with the same filename?

**Comment by benmccann** [comment]
yeah, good point. lol. I guess we can ignore that one for now

**Comment by SuperchupuDev** [comment]
added in c5976cc
