### ISSUE TITLE
Support for helper `convertPathToPattern`

### ISSUE THREAD

**Issue by ematipico** [SuperchupuDev/tinyglobby#40]
I tried to replace `tinyglobby` in the Astro repository, but unfortunately, we use an utility that at the moment isn't ported: [`convertPathToPattern`](https://www.npmjs.com/package/fast-glob#convertpathtopatternpath)

**Comment by SuperchupuDev** [comment]
isn't this the same as #36's `escapePath` function? i can't tell the difference

**Comment by benmccann** [comment]
Pretty similar. The docs says it additionally converts backslashes to forward slashes on Windows in cases where they are not escape characters
