### ISSUE TITLE
Slow performance when globbing shallow files

### ISSUE THREAD

**Issue by bluwy** [SuperchupuDev/tinyglobby#73]
When globbing like `*/package.json` or `*/*/package.json`, it runs very slowly as presumably it's crawling more files recursively like `node_modules`.

```js
import { globSync } from 'tinyglobby'
console.log(globSync('*/package.json', { expandDirectories: false }))
```

When I try with `fast-glob`, it worked fast ootb:

```js
import fg from 'fast-glob'
console.log(fg.globSync('*/package.json'))
```

I'm able to workaround this by adding `ignore: ['**/node_modules/**']` but I shouldn't need to in the first place I believe. And IIUC the paths are still crawled recursively pass the first directory depth unnecessarily as I only specified one-level deep with `*/package.json`.

**Comment by SuperchupuDev** [comment]
should be fixed in #69, however it breaks vite's tests so it can't land until i further investigate

**Comment by SuperchupuDev** [comment]
@bluwy can you check if perf is better in `https://pkg.pr.new/tinyglobby@ee6e02b`

**Comment by bluwy** [comment]
It runs a lot faster now! I added some loggings and it seems to not be overcrawling directories anymore. I'll close this as fixed.
