### ISSUE TITLE
Add debug option to log crawled paths

### ISSUE THREAD

**Issue by bluwy** [SuperchupuDev/tinyglobby#74]
When stumbling on slow globbing, it'd be nice if `tinyglobby` can log the paths being crawled so I know if there are paths I forgot to ignore or being crawled unexpectedly. I've been resorting to patching `filters` and `exclude`:

https://github.com/SuperchupuDev/tinyglobby/blob/0f7bfaa749423f01cc3eb5468a5142340a9ce18b/src/index.ts#L168-L169

Which is a little clunky to implement. Perhaps this could also be implemented directly in `fdir` instead.

**Comment by SuperchupuDev** [comment]
@bluwy is this good enough logging? would be enabled by either setting the `debug` option or setting a `TINYGLOBBY_DEBUG` env flag

![image](https://github.com/user-attachments/assets/508542f7-0fed-4c70-9a8e-c536486aed09)

**Comment by bluwy** [comment]
I was thinking that it could log every paths that're being visited (regardless if filtered out or excluded) so I could figure out if there's unnecessary fs calls on places where it shouldn't. So something like:

```bash
[tinyglobby] crawling /Users/foo/project/
[tinyglobby] crawling /Users/foo/project/test.js
[tinyglobby] crawling /Users/foo/project/test.ts
[tinyglobby] crawling /Users/foo/project/bar/
[tinyglobby] crawling /Users/foo/project/node_modules/
```

If it makes sense. I think what you have now could still be useful being logged at the start, but without logging the crawled paths I think it's a bit hard to deduce which paths are being crawled or not.

**Comment by SuperchupuDev** [comment]
ah, then i need to clarify the wording, the logs that say "excluding path" are the ones from paths that are being crawled, unless their `ignored` or `excluded` properties are true

**Comment by bluwy** [comment]
Ah I see. Then I think we have the same idea then, though logging an object for each crawled paths might be a bit too verbose I think 🤔 Maybe we can strip out some and try to keep it as a single line? but that's only my personal preference.

**Comment by bluwy** [comment]
Thanks for supporting this!
