### ISSUE TITLE
absolute escaped patterns don't work well with non-escaped cwd

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#78]
https://github.com/benmccann/copy-webpack-plugin/tree/tinyglobby

```
 FAIL  test/context-option.test.js
  ● context option › should work when "from" is a file and "context" with special characters

    unable to locate '/home/myuser/copy-webpack-plugin/test/fixtures/\[special$directory\]/directoryfile.txt' glob

      423 |       }
      424 |
    > 425 |       const missingError = new Error(`unable to locate '${glob}' glob`);
          |                            ^
      426 |
      427 |       compilation.errors.push(/** @type {WebpackError} */ (missingError));
      428 |

      at Function.runPattern (src/index.js:425:28)
      at src/index.js:867:34

  ● context option › should work when "from" is a directory and "context" with special characters

    unable to locate '/home/myuser/copy-webpack-plugin/test/fixtures/\[special$directory\]/**/*' glob

      423 |       }
      424 |
    > 425 |       const missingError = new Error(`unable to locate '${glob}' glob`);
          |                            ^
      426 |
      427 |       compilation.errors.push(/** @type {WebpackError} */ (missingError));
      428 |

      at Function.runPattern (src/index.js:425:28)
      at src/index.js:867:34

  ● context option › should work when "from" is a glob and "context" with special characters

    unable to locate '/home/myuser/copy-webpack-plugin/test/fixtures/\[special$directory\]/**/*' glob

      423 |       }
      424 |
    > 425 |       const missingError = new Error(`unable to locate '${glob}' glob`);
          |                            ^
      426 |
      427 |       compilation.errors.push(/** @type {WebpackError} */ (missingError));
      428 |

      at Function.runPattern (src/index.js:425:28)
      at src/index.js:867:34

  ● context option › should work when "from" is a glob and "context" with special characters #2

    unable to locate '/home/myuser/copy-webpack-plugin/test/fixtures/\[special$directory\]/\(special-*file\).txt' glob
```

error is thrown here: https://github.com/benmccann/copy-webpack-plugin/blob/8fc1997406dc08ca6458fe4d4377d9aeb0d9dfe4/src/index.js#L425

**Comment by benmccann** [comment]
Maybe there needs to be some special handling for special characters? https://github.com/micromatch/picomatch?tab=readme-ov-file#matching-special-characters-as-literals

**Comment by SuperchupuDev** [comment]
it looks like the path is escaped first before globbing in your code, so maybe it's `escapePath` that needs to be updated https://github.com/benmccann/copy-webpack-plugin/blob/8fc1997406dc08ca6458fe4d4377d9aeb0d9dfe4/src/index.js#L372

**Comment by benmccann** [comment]
Nice guess, but I don't think that's it. I did a simple check and they seem to both escape `$` the same

```
import fg from 'fast-glob';
import { escapePath } from 'tinyglobby';

console.log(`fast-glob: ${fg.escapePath('a$b')}`);
console.log(`tinyglobby: ${escapePath('a$b')}`);
```

Prints:
```
fast-glob: a$b
tinyglobby: a$b
```

**Comment by benmccann** [comment]
I just noticed that this project uses the `fs` option. I'm guessing that's what it is

https://github.com/benmccann/copy-webpack-plugin/blob/8fc1997406dc08ca6458fe4d4377d9aeb0d9dfe4/src/index.js#L343

https://www.npmjs.com/package/fast-glob#fs

**Comment by SuperchupuDev** [comment]
can you provide a minimal repro? i can't reproduce on linux

**Comment by benmccann** [comment]
The tests don't fail for you on Linux? Are you sure you're on the `tinyglobby` branch of my fork? Or you just haven't been able to come up with a minimal repro?

I haven't been able to come up with a minimal repro. Whatever the issue is it seems quite complicated to reproduce and I'm not sure if I'll really be able to shrink it too much without entirely debugging the issue. I did just find another issue while trying to reproduce it though: https://github.com/SuperchupuDev/tinyglobby/issues/82

**Comment by SuperchupuDev** [comment]
i didn't try your fork, i just made a directory that included `$` and tried to glob it in many different ways, with no issue

**Comment by benmccann** [comment]
I came up with a minimal reproduction: https://github.com/benmccann/copy-webpack-plugin/commit/d473c92cc1a12b25ddfccb63ec5b5d9b2619fad7

Run:
```
git clone git@github.com:benmccann/copy-webpack-plugin.git
cd copy-webpack-plugin
git checkout tinyglobby
npm install
node tinyglobby.js
```

**Comment by SuperchupuDev** [comment]
can repro, has nothing to do with `$` :P. it looks like tinyglobby doesn't realize `\\[special$directory\\]` (from the pattern) and `[special$directory]` (from cwd) are the same. odd but i can see why it happens

**Comment by SuperchupuDev** [comment]
was a one line fix, let me know if escaped patterns produce any other issue :)

**Comment by benmccann** [comment]
Awesome. Thank you!!
