### ISSUE TITLE
`absolute` option does not work when glob pattern is an absolute path

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#82]
```
import fg from 'fast-glob';
import { escapePath, globSync } from 'tinyglobby';

console.log(JSON.stringify(fg.globSync(fg.escapePath('/home/myuser/tmp/test/[special$directory]/(special-*file).txt')), { absolute: true }));
console.log(JSON.stringify(globSync(escapePath('/home/myuser/tmp/test/[special$directory]/(special-*file).txt')), { absolute: true }));
```

Prints:
```
["/home/myuser/tmp/test/[special$directory]/(special-*file).txt"]
["[special$directory]/(special-*file).txt"]
```

**Comment by SuperchupuDev** [comment]
can't seem to reproduce. i notice that in your repro example you are using fast-glob's escapePath instead of tinyglobby's one. what happens if you use the latter?
![image](https://github.com/user-attachments/assets/c22aaeda-41ea-43f7-8575-1c89be4ddaae)

**Comment by benmccann** [comment]
Oops. That wasn't the issue. I dumbly had some mis-matched parens, which meant the `{ absolute: true }` wasn't actually being passed to `tinyglobby`

Thanks for taking a look and sorry I wasted your time on this one
